blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions & Discussions
    url: https://github.com/getumbrel/microservice-architect/discussions
    about: Please use GitHub Discussions for questions and general help