import { DynamicStructuredTool } from "@langchain/core/tools";
import { z } from "zod";
import * as fs from "fs";
import * as path from "path";

/**
 * Generates architecture documentation based on service analysis and dependency mapping.
 * Creates markdown files with:
 * - Architecture overview
 * - Service catalog
 * - Data flow diagrams
 * - API documentation
 */
export const ArchitectureDocumenterTool = new DynamicStructuredTool({
  name: "document_architecture",
  description:
    "Generates comprehensive architecture documentation. Input: outputPath (where to save docs), servicesData (JSON from analyze_service), dependenciesData (JSON from map_dependencies).",
  schema: z.object({
    outputPath: z
      .string()
      .describe("Absolute path where documentation files should be saved"),
    servicesData: z
      .string()
      .describe("JSON string containing service analysis data"),
    dependenciesData: z
      .string()
      .describe("JSON string containing dependency mapping data"),
  }),
  func: async ({ outputPath, servicesData, dependenciesData }) => {
    try {
      const services = JSON.parse(servicesData);
      const dependencies = JSON.parse(dependenciesData);

      // Create output directory
      if (!fs.existsSync(outputPath)) {
        fs.mkdirSync(outputPath, { recursive: true });
      }

      const docs = [];

      // 1. Generate Architecture Overview
      const overview = `# Architecture Overview

## System Description
This documentation describes a microservices architecture with ${dependencies.summary.totalServices} services.

## Statistics
- **Total Services:** ${dependencies.summary.totalServices}
- **HTTP Connections:** ${dependencies.summary.httpConnections}
- **Services with Database:** ${dependencies.summary.servicesWithDatabase}
- **Services with Messaging:** ${dependencies.summary.servicesWithMessaging}

## Technology Stack
${Array.from(new Set(Object.values(services).flatMap((s: any) => s.techStack)))
  .map((tech) => `- ${tech}`)
  .join("\n")}

## Services Catalog
${Object.entries(services)
  .map(
    ([name, data]: [string, any]) => `
### ${name}
- **Tech Stack:** ${data.techStack.join(", ") || "N/A"}
- **Databases:** ${data.databases.join(", ") || "None"}
- **Message Queues:** ${data.messageQueues.join(", ") || "None"}
- **Dependencies:** ${data.dependencies.join(", ") || "None"}
`
  )
  .join("\n")}

## Data Flow
\`\`\`mermaid
graph LR
${dependencies.dependencyGraph.edges
  .map((edge: any) => `    ${edge.from}[${edge.from}] -->|${edge.type}| ${edge.to}[${edge.to}]`)
  .join("\n")}
\`\`\`

---
*Generated by Microservice Architect Agent*
`;

      fs.writeFileSync(path.join(outputPath, "architecture-overview.md"), overview);
      docs.push("architecture-overview.md");

      // 2. Generate Service Catalog
      const catalog = `# Service Catalog

${Object.entries(services)
  .map(
    ([name, data]: [string, any]) => `
## ${name}

**Description:** ${data.serviceName}

### Technical Details
- **Stack:** ${data.techStack.join(", ") || "N/A"}
- **Databases:** ${data.databases.join(", ") || "None"}
- **Message Queues:** ${data.messageQueues.join(", ") || "None"}

### API Endpoints
${
  data.endpoints?.length > 0
    ? data.endpoints.map((ep: string) => `- \`${ep}\``).join("\n")
    : "_No endpoints detected_"
}

### Dependencies
${
  data.dependencies?.length > 0
    ? data.dependencies.map((dep: string) => `- ${dep}`).join("\n")
    : "_No dependencies detected_"
}

### External Services
${
  data.externalServices?.length > 0
    ? data.externalServices.map((svc: string) => `- ${svc}`).join("\n")
    : "_No external services detected_"
}

---
`
  )
  .join("\n")}

*Generated by Microservice Architect Agent*
`;

      fs.writeFileSync(path.join(outputPath, "service-catalog.md"), catalog);
      docs.push("service-catalog.md");

      // 3. Generate API Documentation
      const apiDocs = `# API Documentation

## Endpoints by Service

${Object.entries(services)
  .map(
    ([name, data]: [string, any]) => {
      if (!data.endpoints || data.endpoints.length === 0) return "";
      return `
### ${name}

| Method | Endpoint |
|--------|----------|
${data.endpoints
  .map((ep: string) => {
    const match = ep.match(/(get|post|put|delete|patch)/i);
    const method = match ? match[0].toUpperCase() : "GET";
    const path = ep.replace(/^(get|post|put|delete|patch)/i, "").trim();
    return `| ${method} | \`${path}\` |`;
  })
  .join("\n")}

`;
    }
  )
  .filter(Boolean)
  .join("\n")}

---
*Generated by Microservice Architect Agent*
`;

      fs.writeFileSync(path.join(outputPath, "api-documentation.md"), apiDocs);
      docs.push("api-documentation.md");

      // 4. Generate Dependency Matrix
      const depMatrix = `# Dependency Matrix

## Service Dependencies

| Service | Calls | Called By | Databases | Message Queues |
|---------|-------|-----------|-----------|----------------|
${Object.entries(dependencies.services)
  .map(
    ([name, data]: [string, any]) =>
      `| ${name} | ${data.calls.join(", ") || "-"} | ${data.calledBy.join(", ") || "-"} | ${data.sharedDatabases.join(", ") || "-"} | ${
        [...data.publishesTo, ...data.subscribesTo].join(", ") || "-"
      } |`
  )
  .join("\n")}

## Communication Patterns

### HTTP Calls
${dependencies.dependencyGraph.edges
  .map((edge: any) => `- **${edge.from}** → **${edge.to}** (${edge.type})`)
  .join("\n")}

### Message Flows
${Object.entries(dependencies.services)
  .flatMap(([name, data]: [string, any]) => [
    ...data.publishesTo.map((topic: string) => `- **${name}** publishes to \`${topic}\``),
    ...data.subscribesTo.map((topic: string) => `- **${name}** subscribes to \`${topic}\``),
  ])
  .join("\n") || "_No message flows detected_"}

---
*Generated by Microservice Architect Agent*
`;

      fs.writeFileSync(path.join(outputPath, "dependency-matrix.md"), depMatrix);
      docs.push("dependency-matrix.md");

      return JSON.stringify(
        {
          success: true,
          generatedFiles: docs,
          outputPath,
          summary: {
            totalServices: dependencies.summary.totalServices,
            totalFiles: docs.length,
          },
        },
        null,
        2
      );
    } catch (error) {
      return `Error generating documentation: ${error instanceof Error ? error.message : String(error)}`;
    }
  },
});
