import { tool } from "@langchain/core/tools";
import { z } from "zod";
import * as fs from "fs";
import * as path from "path";

/**
 * Generates comprehensive architecture documentation
 * including README, architecture diagrams, and API docs.
 */
export const ArchitectureDocumenterTool = tool(
  async (input: {
    outputPath: string;
    servicesData: string;
    dependenciesData: string;
  }) => {
    const { outputPath, servicesData, dependenciesData } = input;
    const resolvedOutputPath = path.resolve(outputPath);

    // Ensure output directory exists
    if (!fs.existsSync(resolvedOutputPath)) {
      fs.mkdirSync(resolvedOutputPath, { recursive: true });
    }

    const services = JSON.parse(servicesData);
    const dependencies = JSON.parse(dependenciesData);

    const result: Record<string, any> = {
      filesGenerated: [],
      summary: {
        totalServices: Object.keys(services).length,
        totalConnections: dependencies.connections?.length || 0,
        sharedDatabases: dependencies.sharedDatabases || [],
        messageQueues: dependencies.messageQueues || [],
      },
    };

    // Generate main README.md
    const readme = generateReadme(services, dependencies);
    const readmePath = path.join(resolvedOutputPath, "README.md");
    fs.writeFileSync(readmePath, readme);
    result.filesGenerated.push("README.md");

    // Generate architecture diagram (Mermaid)
    const diagram = generateArchitectureDiagram(services, dependencies);
    const diagramPath = path.join(resolvedOutputPath, "ARCHITECTURE.md");
    fs.writeFileSync(diagramPath, diagram);
    result.filesGenerated.push("ARCHITECTURE.md");

    // Generate API documentation
    const apiDocs = generateApiDocs(services);
    const apiDocsPath = path.join(resolvedOutputPath, "API.md");
    fs.writeFileSync(apiDocsPath, apiDocs);
    result.filesGenerated.push("API.md");

    // Generate service-specific docs
    const servicesDir = path.join(resolvedOutputPath, "services");
    fs.mkdirSync(servicesDir, { recursive: true });

    for (const [serviceName, serviceData] of Object.entries(services)) {
      const serviceDoc = generateServiceDoc(serviceName, serviceData as any);
      const serviceDocPath = path.join(servicesDir, `${serviceName}.md`);
      fs.writeFileSync(serviceDocPath, serviceDoc);
      result.filesGenerated.push(`services/${serviceName}.md`);
    }

    // Generate dependency graph
    const depGraph = generateDependencyGraph(dependencies);
    const depGraphPath = path.join(resolvedOutputPath, "DEPENDENCIES.md");
    fs.writeFileSync(depGraphPath, depGraph);
    result.filesGenerated.push("DEPENDENCIES.md");

    return JSON.stringify(result, null, 2);
  },
  {
    name: "document_architecture",
    description: "Generates comprehensive architecture documentation including README, diagrams, and API docs",
    schema: z.object({
      outputPath: z.string().describe("Directory where documentation will be generated"),
      servicesData: z.string().describe("JSON string of analyzed services data"),
      dependenciesData: z.string().describe("JSON string of mapped dependencies data"),
    }),
  }
);

function generateReadme(
  services: Record<string, any>,
  dependencies: Record<string, any>
): string {
  const serviceCount = Object.keys(services).length;
  const connectionCount = dependencies.connections?.length || 0;

  return `# Microservice Architecture Documentation

## 📊 Overview

This document provides a comprehensive overview of the microservice architecture.

| Metric | Count |
|--------|-------|
| Total Services | ${serviceCount} |
| Inter-service Connections | ${connectionCount} |
| Shared Databases | ${(dependencies.sharedDatabases || []).length} |
| Message Queues | ${(dependencies.messageQueues || []).length} |

## 🏗️ Services

${Object.entries(services)
  .map(([name, data]) => {
    const stack = (data as any).techStack;
    return `### ${name}
- **Framework**: ${stack?.framework || "Unknown"}
- **Runtime**: ${stack?.runtime || "Unknown"}
- **Endpoints**: ${((data as any).endpoints || []).length}
- **Databases**: ${((data as any).databases || []).join(", ") || "None"}`;
  })
  .join("\n\n")}

## 📚 Documentation Structure

- [README.md](./README.md) - This file (overview)
- [ARCHITECTURE.md](./ARCHITECTURE.md) - Architecture diagrams
- [API.md](./API.md) - API documentation
- [DEPENDENCIES.md](./DEPENDENCIES.md) - Dependency graph
- [services/](./services/) - Individual service documentation

## 🚀 Getting Started

See individual service documentation in the \`services/\` directory for setup instructions.

---
*Generated by Microservice Architect Agent*
`;
}

function generateArchitectureDiagram(
  services: Record<string, any>,
  dependencies: Record<string, any>
): string {
  const serviceNames = Object.keys(services);
  const connections = dependencies.connections || [];

  let mermaid = `# Architecture Diagram

## System Overview

\`\`\`mermaid
graph TB
`;

  // Add service nodes
  for (const name of serviceNames) {
    const data = services[name];
    const databases = (data.databases || []).join(", ");
    mermaid += `  ${name}[${name}\n${databases ? `🗄️ ${databases}` : ""}]\n`;
  }

  // Add database nodes
  for (const db of dependencies.sharedDatabases || []) {
    mermaid += `  ${db.toLowerCase().replace(/\s/g, "-")}[((${db}\nDatabase))]\n`;
  }

  // Add message queue nodes
  for (const mq of dependencies.messageQueues || []) {
    mermaid += `  ${mq.toLowerCase().replace(/\s/g, "-")}[${mq}\nQueue]\n`;
  }

  // Add connections
  for (const conn of connections) {
    const label = conn.type === "http" ? "HTTP" : conn.type;
    mermaid += `  ${conn.from} --${label}--> ${conn.to}\n`;
  }

  // Connect services to databases
  for (const [name, data] of Object.entries(services)) {
    for (const db of (data as any).databases || []) {
      const dbId = db.toLowerCase().replace(/\s/g, "-");
      mermaid += `  ${name} --uses--> ${dbId}\n`;
    }
  }

  mermaid += `\`\`\`

## Service Communication

${connections.length > 0
  ? connections
      .map((c) => `- **${c.from}** → **${c.to}** (${c.type})`)
      .join("\n")
  : "_No inter-service connections detected._"}

## Data Layer

${(dependencies.sharedDatabases || []).length > 0
  ? `Shared databases:\n${dependencies.sharedDatabases
      .map((db: string) => `- ${db}`)
      .join("\n")}`
  : "_No shared databases detected._"}

## Messaging

${(dependencies.messageQueues || []).length > 0
  ? `Message queues in use:\n${dependencies.messageQueues
      .map((mq: string) => `- ${mq}`)
      .join("\n")}`
  : "_No message queues detected._"}

## Service Registry

${dependencies.serviceRegistry
  ? `Using: **${dependencies.serviceRegistry}**`
  : "_No service registry detected._"}
`;

  return mermaid;
}

function generateApiDocs(services: Record<string, any>): string {
  let docs = `# API Documentation

## Services Overview

| Service | Endpoints | Framework |
|---------|-----------|-----------|
`;

  for (const [name, data] of Object.entries(services)) {
    const endpoints = (data as any).endpoints || [];
    const framework = (data as any).techStack?.framework || "Unknown";
    docs += `| ${name} | ${endpoints.length} | ${framework} |\n`;
  }

  docs += "\n## Endpoints by Service\n\n";

  for (const [name, data] of Object.entries(services)) {
    const endpoints = (data as any).endpoints || [];
    if (endpoints.length === 0) continue;

    docs += `### ${name}\n\n`;
    docs += "| Method | Path |\n";
    docs += "|--------|------|\n";

    for (const endpoint of endpoints) {
      const [method, path] = endpoint.split(" ");
      docs += `| ${method} | \`${path}\` |\n`;
    }

    docs += "\n";
  }

  docs += `\n## Environment Variables

${Object.entries(services)
  .map(([name, data]) => {
    const envVars = (data as any).envVars || [];
    if (envVars.length === 0) return "";
    return `### ${name}\n${envVars.map((v: string) => `- \`${v}\``).join("\n")}`;
  })
  .filter(Boolean)
  .join("\n\n")}
`;

  return docs;
}

function generateServiceDoc(name: string, data: any): string {
  const stack = data.techStack || {};
  const endpoints = data.endpoints || [];
  const databases = data.databases || [];
  const envVars = data.envVars || [];

  return `# ${name} Service

## Overview

${data.description || `The ${name} microservice.`}

## Tech Stack

- **Language**: ${stack.language || "Unknown"}
- **Runtime**: ${stack.runtime || "Unknown"}
- **Framework**: ${stack.framework || "Unknown"}

## Dependencies

### Production
${(stack.dependencies || [])
  .slice(0, 10)
  .map((d: string) => `- ${d}`)
  .join("\n") || "_No dependencies detected._"}

### Development
${(stack.devDependencies || [])
  .slice(0, 10)
  .map((d: string) => `- ${d}`)
  .join("\n") || "_No dev dependencies detected._"}

## API Endpoints

${endpoints.length > 0
  ? endpoints.map((e: string) => `- \`${e}\``).join("\n")
  : "_No endpoints detected._"}

## Data Layer

${databases.length > 0
  ? databases.map((d: string) => `- ${d}`).join("\n")
  : "_No databases detected._"}

## Configuration

### Environment Variables

${envVars.length > 0
  ? envVars.map((v: string) => `- \`${v}\``).join("\n")
  : "_No environment variables detected._"}

## Docker Configuration

${data.docker
  ? `- **Base Image**: ${data.docker.baseImage || "Unknown"}
- **Exposed Ports**: ${data.docker.ports.join(", ") || "None"}
- **Commands**: ${data.docker.commands.join("; ") || "None"}`
  : "_No Docker configuration detected._"}

---

*Path*: \`${data.path}\`
`;
}

function generateDependencyGraph(dependencies: Record<string, any>): string {
  const connections = dependencies.connections || [];
  const services = Object.keys(dependencies.services || {});

  let graph = `# Dependency Graph

## Overview

This document shows the relationships between services in the architecture.

## Connection Matrix

\`&#96;&#96;&#96;mermaid
flowchart LR
`;

  // Group connections by type
  const connectionsByType: Record<string, typeof connections> = {};
  for (const conn of connections) {
    if (!connectionsByType[conn.type]) {
      connectionsByType[conn.type] = [];
    }
    connectionsByType[conn.type].push(conn);
  }

  // Generate subgraphs for each connection type
  for (const [type, conns] of Object.entries(connectionsByType)) {
    graph += `  subgraph ${type}[${type.toUpperCase()} Connections]\n`;
    for (const conn of conns) {
      graph += `    ${conn.from}-->${conn.to}\n`;
    }
    graph += "  end\n";
  }

  graph += `\`\`\`

## Connection Types

${Object.entries(connectionsByType)
  .map(([type, conns]) => {
    return `### ${type.toUpperCase()}
${conns
  .map((c) => `- **${c.from}** → **${c.to}**`)
  .join("\n")}`;
  })
  .join("\n\n") || "_No connections detected._"}

## Service Dependencies

| Service | Dependencies | Provides To |
|---------|-------------|-------------|
`;

  for (const [name, data] of Object.entries(dependencies.services || {})) {
    const dependsOn = (data as any).dependsOn?.join(", ") || "None";
    const providesTo = connections
      .filter((c) => c.to === name)
      .map((c) => c.from)
      .join(", ") || "None";
    graph += `| ${name} | ${dependsOn} | ${providesTo} |\n`;
  }

  return graph;
}