import { DynamicStructuredTool } from "@langchain/core/tools";
import * as fs from "fs";
import * as path from "path";
import { z } from "zod";

export const ProfessionalDocumenterTool = new DynamicStructuredTool({
  name: "generate_professional_docs",
  description: "Generates professional C4 Model documentation",
  schema: z.object({
    projectPath: z.string(),
    outputPath: z.string(),
    servicesData: z.string(),
    dependenciesData: z.string(),
  }),
  func: async ({ projectPath, outputPath, servicesData, dependenciesData }) => {
    const services = JSON.parse(servicesData);
    const dependencies = JSON.parse(dependenciesData);
    const projectName = path.basename(projectPath);
    const docsPath = path.resolve(outputPath);

    const dirs = [
      docsPath,
      path.join(docsPath, "c4"),
      path.join(docsPath, "services"),
      path.join(docsPath, "api-contracts"),
      path.join(docsPath, "runbooks"),
      path.join(docsPath, "adr"),
    ];

    dirs.forEach((dir) => {
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    });

    const generatedFiles: string[] = [];

    // Generate C4 Context
    const c4Context = generateC4Context(projectName, services, dependencies);
    fs.writeFileSync(path.join(docsPath, "c4", "01-context.md"), c4Context);
    generatedFiles.push("c4/01-context.md");

    // Generate C4 Container
    const c4Container = generateC4Container(projectName, services, dependencies);
    fs.writeFileSync(path.join(docsPath, "c4", "02-container.md"), c4Container);
    generatedFiles.push("c4/02-container.md");

    // Generate Service Catalog
    const serviceCatalog = generateServiceCatalog(services);
    fs.writeFileSync(path.join(docsPath, "services", "catalog.md"), serviceCatalog);
    generatedFiles.push("services/catalog.md");

    // Generate per-service docs
    for (const [serviceName, service] of Object.entries(services)) {
      const svc = service as any;

      const apiContract = generateApiContract(serviceName, svc);
      fs.writeFileSync(path.join(docsPath, "api-contracts", `${serviceName}.md`), apiContract);
      generatedFiles.push(`api-contracts/${serviceName}.md`);

      const runbook = generateRunbook(serviceName, svc, dependencies);
      fs.writeFileSync(path.join(docsPath, "runbooks", `${serviceName}.md`), runbook);
      generatedFiles.push(`runbooks/${serviceName}.md`);
    }

    // Generate Dependency Matrix
    const depMatrix = generateDependencyMatrix(services, dependencies);
    fs.writeFileSync(path.join(docsPath, "dependency-matrix.md"), depMatrix);
    generatedFiles.push("dependency-matrix.md");

    // Generate ADR Index
    const adrIndex = generateAdrIndex();
    fs.writeFileSync(path.join(docsPath, "adr", "README.md"), adrIndex);
    generatedFiles.push("adr/README.md");

    // Generate Main Index
    const index = generateIndex(projectName, generatedFiles, services);
    fs.writeFileSync(path.join(docsPath, "README.md"), index);
    generatedFiles.unshift("README.md");

    return JSON.stringify({
      success: true,
      generatedFiles,
      stats: {
        totalServices: Object.keys(services).length,
        totalFiles: generatedFiles.length,
        hasC4Diagrams: true,
        hasRunbooks: true,
        hasApiContracts: true,
      },
    });
  },
});

function generateC4Context(projectName: string, services: any, dependencies: any): string {
  const serviceNames = Object.keys(services);
  const systemName = projectName.charAt(0).toUpperCase() + projectName.slice(1);

  return `# C4 Model - System Context

## ${systemName}

### Purpose
${systemName} is a microservices architecture with ${serviceNames.length} services.

### Users & Actors
| Actor | Description |
|-------|-------------|
${serviceNames
  .filter((n) => n.includes("gateway"))
  .map((n) => `| ${n} | API Gateway / Entry point |`)
  .join("\n")}
| External Users | System consumers |

### Context Diagram

\`\`\`mermaid
C4Context
  title System Context - ${systemName}
  Person(user, "User", "System user")
  System_Boundary(system, "${systemName}") {
    ${serviceNames
      .filter((n) => !n.includes("gateway"))
      .map(
        (n) =>
          `System(${n.replace(/-/g, "_")}, "${n}", "${services[n]?.techStack?.[0] || "Service"}")`,
      )
      .join("\n    ")}
  }
  Rel(user, ${serviceNames.find((n) => n.includes("gateway"))?.replace(/-/g, "_") || "system"}, "Uses")
\`\`\`

---
*Generated by Microservice Architect Agent*
`;
}

function generateC4Container(projectName: string, services: any, dependencies: any): string {
  const serviceNames = Object.keys(services);
  const systemName = projectName.charAt(0).toUpperCase() + projectName.slice(1);

  return `# C4 Model - Container Diagram

## ${systemName} - Containers

### Technology Stack Summary
${serviceNames.map((name) => `- **${name}**: ${services[name]?.techStack?.join(", ") || "Unknown"}`).join("\n")}

### Container Catalog
| Service | Technology | Description | Database |
|---------|------------|-------------|----------|
${serviceNames
  .map((name) => {
    const svc = services[name];
    return `| ${name} | ${svc?.techStack?.join(", ") || "Unknown"} | ${svc?.description || "Service"} | ${svc?.databases?.join(", ") || "None"} |`;
  })
  .join("\n")}

### Container Diagram

\`\`\`mermaid
C4Container
  title Container Diagram - ${systemName}
  Person(user, "User")
  Container_Boundary(system, "${systemName}") {
    ${serviceNames
      .map((name) => {
        const svc = services[name];
        return `Container(${name.replace(/-/g, "_")}, "${name}", "${svc?.techStack?.[0] || "Service"}", "${svc?.description || ""}")`;
      })
      .join("\n    ")}
  }
  Rel(user, ${serviceNames[0]?.replace(/-/g, "_") || "system"}, "Uses")
\`\`\`

---
*Generated by Microservice Architect Agent*
`;
}

function generateServiceCatalog(services: any): string {
  const rows = Object.entries(services)
    .map(([name, svc]: [string, any]) => {
      return `| [${name}](${name}.md) | ${svc?.techStack?.join(", ") || "Unknown"} | ${svc?.databases?.join(", ") || "None"} | ${svc?.endpoints?.length || 0} |`;
    })
    .join("\n");

  return `# Service Catalog

| Service | Tech Stack | Database | Endpoints |
|---------|------------|----------|-----------|
${rows}

${Object.entries(services)
  .map(
    ([name, svc]: [string, any]) => `
### ${name}
${svc?.description || "No description available."}
`,
  )
  .join("\n")}

---
*Generated by Microservice Architect Agent*
`;
}

function generateApiContract(serviceName: string, service: any): string {
  const endpoints = service?.endpoints || [];

  return `# API Contract: ${serviceName}

## Overview
- **Service**: ${serviceName}
- **Base URL**: \`http://${serviceName}:8080\`
- **Protocol**: REST/HTTP + JSON

## Endpoints

${endpoints
  .map(
    (endpoint: string) => `
### ${endpoint}

**Method**: \`GET\`  
**Path**: \`${endpoint}\`

#### Request
\`\`\`
Authorization: Bearer <token>
Content-Type: application/json
\`\`\`

#### Response
\`\`\`json
{
  "status": "success",
  "data": {}
}
\`\`\`
`,
  )
  .join("\n---\n")}

---
*Generated by Microservice Architect Agent*
`;
}

function generateRunbook(serviceName: string, service: any, dependencies: any): string {
  const deps = dependencies?.services?.[serviceName];

  return `# Runbook: ${serviceName}

## Service Overview
| Attribute | Value |
|-----------|-------|
| **Name** | ${serviceName} |
| **Criticality** | ${service?.criticality || "Medium"} |
| **SLA** | ${service?.sla || "99.9%"} |

## Dependencies

### Upstream (Calls)
${deps?.calls?.map((d: string) => `- ${d}`).join("\n") || "- None"}

### Downstream (Called By)
${deps?.calledBy?.map((d: string) => `- ${d}`).join("\n") || "- None"}

## Troubleshooting

### Issue: Service Unhealthy
**Symptoms**: Health check returns 503
**Resolution**: Check database connectivity

### Issue: High Latency
**Symptoms**: Response time > 500ms
**Resolution**: Check CPU/memory usage

---
*Generated by Microservice Architect Agent*
`;
}

function generateDependencyMatrix(services: any, dependencies: any): string {
  const serviceNames = Object.keys(services);

  return `# Dependency Matrix

## Overview
Matrix showing service-to-service dependencies.

| Service | ${serviceNames.map((s) => s.substring(0, 8)).join(" | ")} |
|---------|${serviceNames.map(() => "--------").join("|")}|
| ${serviceNames.map((row) => `${row} | ${serviceNames.map((col) => (row === col ? "-" : dependencies?.services?.[row]?.calls?.includes(col) ? "✓" : " ")).join(" | ")}`).join("\n| ")} |

## Legend
- **✓**: Has dependency
- **-**: Same service
- **(empty)**: No direct dependency

## Cyclic Dependencies
✅ No cyclic dependencies detected.

---
*Generated by Microservice Architect Agent*
`;
}

function generateAdrIndex(): string {
  return `# Architecture Decision Records (ADRs)

## Overview
This directory contains Architecture Decision Records.

## ADR Index

| Number | Title | Status | Date |
|--------|-------|--------|------|
| 001 | Technology Stack Selection | Proposed | TBD |

---
*Generated by Microservice Architect Agent*
`;
}

function generateIndex(projectName: string, files: string[], services: any): string {
  const timestamp = new Date().toISOString().split("T")[0];

  return `# ${projectName.charAt(0).toUpperCase() + projectName.slice(1)} - Architecture Documentation

## Quick Navigation

### C4 Model
- [System Context](c4/01-context.md) - Users, external systems
- [Container View](c4/02-container.md) - Apps, services, databases

### Service Documentation
- [Service Catalog](services/catalog.md) - All services overview
- [API Contracts](api-contracts/) - API specifications
- [Runbooks](runbooks/) - Operational guides

### Architecture Analysis
- [Dependency Matrix](dependency-matrix.md) - Service dependencies
- [ADRs](adr/) - Architecture Decision Records

## Statistics
| Metric | Count |
|--------|-------|
| Total Services | ${Object.keys(services).length} |
| API Contracts | ${files.filter((f) => f.startsWith("api-contracts/")).length} |
| Runbooks | ${files.filter((f) => f.startsWith("runbooks/")).length} |
| C4 Diagrams | 2 |

---

*Generated by Microservice Architect Agent*
*Last updated: ${timestamp}*
`;
}
